image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V 
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
  - training

train-model:
  stage: training
  script: 
      - pip install --upgrade --force-reinstall . "awscli>1.20.30"
      - export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
      - export PYTHONUNBUFFERED=TRUE
      - export SAGEMAKER_PROJECT_NAME_BRANCH="${SAGEMAKER_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}"
      - |
        run-pipeline --module-name pipelines.abalone.pipeline \
          --role-arn $SAGEMAKER_PIPELINE_ROLE_ARN \
          --tags "[{\"Key\":\"sagemaker:project-name\", \"Value\":\"${SAGEMAKER_PROJECT_NAME}\"}, {\"Key\":\"sagemaker:project-id\", \"Value\":\"${SAGEMAKER_PROJECT_ID}\"}, {\"Key\":\"sagemaker:project-branch\", \"Value\":\"${CI_COMMIT_REF_SLUG}\"}]" \
          --kwargs "{\"region\":\"${AWS_REGION}\",\"sagemaker_project_arn\":\"${SAGEMAKER_PROJECT_ARN}\",\"role\":\"${SAGEMAKER_PIPELINE_ROLE_ARN}\",\"default_bucket\":\"${ARTIFACT_BUCKET}\",\"pipeline_name\":\"${SAGEMAKER_PROJECT_NAME_BRANCH}\",\"model_package_group_name\":\"${SAGEMAKER_PROJECT_NAME_BRANCH}\",\"base_job_prefix\":\"${SAGEMAKER_PROJECT_NAME_BRANCH}\"}"
      - echo "Create/Update of the SageMaker Pipeline and execution completed."
